name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: deps
        run: python -m pip install -U pip wheel setuptools auditwheel

      - name: wheel
        run: python setup.py bdist_wheel

      - name: auditwheel
        if: contains(matrix.os, 'ubuntu')
        run: |
          python -m auditwheel repair dist/*-linux_x86_64.whl --plat manylinux2014_x86_64
